spring:
  application:
    name: zerori
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ADDRESS}:3306/zeroplanet?autoReconnect=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.daum.net
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 10485760
      max-request-size: 10485760
#  jpa:
#    hibernate:
#      ddl-auto: validate
social:
  kakao:
    url: https://kapi.kakao.com
    appId: ${KAKAO_APPID}
    adminKey: ${KAKAO_ADMINKEY}
  apple:
    url: https://appleid.apple.com
    appId: ${APPLE_APPID}
  naver:
    url: https://openapi.naver.com
jwt:
  key: ${JWT_KEY}

github:
  models:
    url: https://models.inference.ai.azure.com
    apiKey: ${GITHUB_MODELS_APIKEY}

cloud:
  aws:
    s3:
      bucket: zeroplanet-bucket
      region:
        static: ap-northeast-2
      stack:
        auto: false
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}

server:
  port: 8080

sentry:
  dsn: ${SENTRY_DSN}
  stacktrace:
    app-packages:
      - com.mozi.moziserver

slack:
  webhook:
    blocked-info: ${SLACK_WEBHOOK_BLOCKED_INFO}
