name: CI/CD

on:
  push:
    tags:
      - 'v*.*.*'

# Need to Consider about permission
# permissions:
#   contents: read

jobs:
  CI-CD:
  
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    ## env setting
#     - name: Set env
#       run: |
#         echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV"
#         echo "GITHUB_ENV VALUE IS $GITHUB_ENV"
        
    ## jdk setting
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    ## gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
  
    ## gradle build
    - name: Build with Gradle
      run: ./gradlew build -x test
      
    ## docker tasks
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with: 
        registry: ${{ secrets.HOST_DEV }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push
#       if: contains(github.ref, 'main')
      run: |
        docker build -t ${{ secrets.HOST_DEV }}/mozi-server:prod .
        docker push ${{ secrets.HOST_DEV }}/mozi-server:prod
    
    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ${{ secrets.USERNAME_PROD }}
        key: ${{ secrets.KEY_PROD }}
        script: sudo ./server-deploy.sh
  
  ## time
  current-time:
  
    needs: CI-CD
    
    runs-on: ubuntu-latest
    
    steps:
    
      # Need to Verify the action
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH:mm:ss
          utcOffset: "+09:00" # 기준이 UTC이기 때문에 한국시간인 KST를 맞추기 위해 +9시간 추가

      - name: Print Current Time
        run: echo "Current Time=${{steps.current-time.outputs.formattedTime}}" # current-time 에서 지정한 포맷대로 현재 시간 출력
        shell: bash
